### ISSUE TITLE
How does this Integrate with SVN

### ISSUE THREAD

**Issue by txappmkr** [scmenthusiast/jira-scm-activity-misc#1]
Team,
How does this integrate with SVN ? could you provide some information/help links on step by step guide to SVN and how the tagging to a EPIC or an ISSUe happens with in this plugin?
Any help would be appreciated

**Comment by scmenthusiast** [comment]
Try these subversion hooks by enabling config option (svn.branch.tags.processing : true), See link https://github.com/scmenthusiast/jira-scm-activity-plugin/tree/master/triggers/subversion

For plugin configuration see quick start document, https://github.com/scmenthusiast/jira-scm-activity-plugin/wiki/JIRA-SCM-Activity-Plugin-Quick-Start
