### ISSUE TITLE
Postgresql Support

### ISSUE THREAD

**Issue by ydgitu** [scmenthusiast/jira-scm-activity-misc#3]
Is it working on postgresql ? If yes, what will be JDBC url ?

**Comment by scmenthusiast** [comment]
Hi At moment only MS SQL Server, MySQL, SQLite databases are supported. I will introduce support PostgreSQL in next release of this plugin.

**Comment by scmenthusiast** [comment]
Introduced support for PostgreSQL in v1.4. Please verify and let me know if any issues.
