### ISSUE TITLE
SCM Activity Plugin doesn't allow sort by date, id, branch

### ISSUE THREAD

**Issue by pkahn-attivio** [scmenthusiast/jira-scm-activity-misc#4]
The Plugin is great and at present it provides a list of Revisions sorted only by revision id.  My users would columns supporting sort for revision, branch, date.

If you point me at the repository containing plugin source, I'll gladly try to implement and send you a pull request for review.

**Comment by scmenthusiast** [comment]
Hi I am publishing plugin source on gitlab by this weekend and will give you the project link.

**Comment by scmenthusiast** [comment]
By default SCM Activities are sorted descending order by date.

**Comment by pkahn-attivio** [comment]
Yeah, I think folks want something akin to an issue navigator with each piece of meta data stored in a column upon which we can sort.  I wrote a sync tool to catch a github webhook payload and push to the plugin's REST api which work and I can play with 'revision' text to force an order but in some cases they want to see changes on a branch and others chronological order and other grouping by id.  so, one order can't meet all their needs.

Once your code is up on gitlab, I'll take a stab at it and send you what I find.  This one may be a stretch for me.

**Comment by pkahn-attivio** [comment]
Hi any news on the plugin source's availability?  I'd like to fork and begin work on this feature - then you can decide if you want it.

Thanks

Peter

**Comment by scmenthusiast** [comment]
My apologies for delay.
Here you go, [https://gitlab.com/scmenthusiast/jira-scm-activity-plugin](https://gitlab.com/scmenthusiast/jira-scm-activity-plugin)

**Comment by scmenthusiast** [comment]
Here you go, https://github.com/scmenthusiast/jira-scm-activity-plugin
