### ISSUE TITLE
Rest API allows creation of SCMActivity changeset using a text ID, but only works to fetch changesets with numeric ID

### ISSUE THREAD

**Issue by Newbury02** [scmenthusiast/jira-scm-activity-misc#5]
I can create a changeset using the SCMActivity rest API, an use a change id of "Test", and it will be created.  But I can only get the record back, if a change id value is numeric.

**Comment by scmenthusiast** [comment]
Thank you for heads-up. I have fixed and released v1.5

**Comment by Newbury02** [comment]
After applying update, the rest services are no longer working.  Any advice?

**Comment by scmenthusiast** [comment]
Hi. After deploying/updating the plugin. please try to initialize plugin by clicking issue tab "Scm Activity" panel and then try rest calls.

**Comment by scmenthusiast** [comment]
I will enable auto initialize in next release.
